### PR TITLE
by default do not install chrony during kickstart

### PR DESCRIPTION
**Pull request by martbhell**
disable by setting this ansible variable:

dhcp_kickstart_do_not_install_chrony: False

### CODE REVIEW

**Comment by khappone** [comment]
Actually, Could we remove a negation here to make it clearer? How about a variable, and the default
dhcp_kickstart_install_chrony: False

**Comment by martbhell** [comment]
Yes :)

**Comment by martbhell** [comment]
Better now?

**Comment by khappone** [comment]
Much, I'll merge once the checks complete

**Pull request merged**
